url: "https://sahyadri-archives.github.io/"
baseurl: "trial1/"
title: Sahyadri Connect
title: Sahyadri Connect

# Your name to show in the footer
author: Sahyadri

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Activities: "activities"
  Krishnamurti: "kfi"
  Newsletter: "posts"
  Resources:
    - Photos: "photos"
    - Videos: "videos"
    - Ninad: "ninad"
  Information:
    - Communication: "comms"

  # _config.yml
################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
#avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
#round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image

# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: 


# Add the website title to the title of every page
title-on-all-pages: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: false

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false

# Personalize the colours in your website. Colour values can be any valid CSS colour

page-col: "#FFFFFF"
text-col: "#3E3830"
link-col: "#A67C52"
hover-col: "#8FA186"
navbar-col: "#668571"
navbar-hover-col: "#8FA186"
navbar-text-col: "#D0DAC8"
navbar-border-col: "#BBC4B4"
footer-col: "#B2C2AD"
footer-text-col: "#3E3830"
footer-link-col: "#A67C52"
footer-hover-col: "#668571"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
site-css:
  - "/assets/css/custom-styles.css"


# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"


kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts" # Settings for the _posts folder
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
      type: "activities" # Settings for the _activities folder
    values:
      layout: "events"
      comments: true
      social-share: true
  -
    scope:
      path: ""
      type: "posts"
    values:
       layout: "profile"
       comments: true
       social-share: true
  -
    scope:
      path: "" # Default for regular pages (index.md, etc.)
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - vendor/
  - node_modules/
  - .github/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /posts/:title

  activities:
    output: true
    permalink: /activities/:title/

  profiles:
    output: true
    permalink: /profiles/:title/
 
